language: node_js
node_js:
  - 14
cache: yarn
notifications:
  email: false
install:
  - yarn install
services:
  - postgresql
  - redis
script:
  - yarn test2
before_script:
  - psql -c 'create database aboyeji_barnes_backstars_test;' -U postgres
