language: node_js
node_js:
  - 12
cache: yarn
install:
  - yarn install
services:
  - postgresql
  - redis-server
script:
  - yarn test
before_script:
  - psql -c 'create database aboyeji-barnes-backstars-test;' -U postgres
